apiVersion: v1
data:
    mapRoles: |
        - groups:
          - system:bootstrappers
          - system:nodes
          rolearn: arn:aws:iam::746129416259:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-W4XRVRLCW47K
          username: system:node:{{EC2PrivateDNSName}}
          - rolearn: arn:aws:iam::746129416259:role/UdacityFlaskDeployCBKubectlRole
          username: build
          groups:
            - system:masters

    mapUsers: |
        []
kind: ConfigMap
metadata:
    creationTimestamp: "2020-06-19T04:55:11Z"
    name: aws-auth
    namespace: kube-system
    resourceVersion: "836"
    selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
    uid: 5cfce689-3f13-4148-8ff6-168f0de4617b
